"""
Record and cache expected output Parquet data for end-to-end (E2E) tests.

This module is a one-off utility that is intended to be run locally on demand to (re)generate the
known output fixtures used by the E2E test suite.

Why this exists
---------------
The E2E tests validate the processor by comparing the Parquet files produced by a run (written to the E2E output bucket)
against a set of known-good expected outputs stored on disk under ``tests/data/outputs/end_to_end``.

Those expected outputs are *not* hand-written: they are generated by running the real processing pipeline for each
E2E test case and then downloading the resulting Parquet outputs from S3 to the fixture directory.

Usage pattern
-------------
Developers should run this script whenever changes could alter the expected E2E outputs, for example:
- metadata changes (new/updated configs, dependencies, dataset mappings)
- processing logic changes (QC, infill, corrections, aggregation, derivations)

Review requirement
------------------
Regenerating these outputs is a high-impact change. After running this script, developers must manually review the
updated Parquet outputs to ensure the values and structure are sensible and represent the intended behaviour of the
processor. Only then should the outputs be committed and used for E2E testing.
"""

import os
import shutil
from pathlib import Path
from unittest.mock import patch

import polars as pl
from tests.end_to_end.mock_metadata_api.mock_api import mock_metadata_api
from tests.utils.eddypro_test_helpers import eddypro_mock_init, eddypro_mock_run
from tests.utils.fixture_helpers import END_TO_END, TEST_DATA_OUTPUT_DIR, load_json_file
from tests.utils.metadata_helpers import E2E_OUTPUT_BUCKET
from tests.utils.s3_test_helpers import get_s3_storage_client

from dritimeseriesprocessor.__main__ import main as pipeline_main
from dritimeseriesprocessor.operations.eddypro.eddypro_runner import EddyProRunner


def reset_output_data_fixture_dir(path: Path) -> None:
    """Delete and recreate the output data fixture directory.

    Args:
        path: Directory path to reset.
    """
    shutil.rmtree(path, ignore_errors=True)
    path.mkdir(parents=True, exist_ok=True)


def main() -> None:
    # run the processing pipeline for each test case and intercept the results to save as cached test output data
    with mock_metadata_api() as metadata_api_url:
        os.environ["metadata_api_url"] = metadata_api_url

        with get_s3_storage_client() as storage_client:
            expected_output_dir = TEST_DATA_OUTPUT_DIR / "end_to_end"
            reset_output_data_fixture_dir(expected_output_dir)

            test_cases = load_json_file(END_TO_END / "test_cases.json")["test_cases"]
            for test_case in test_cases:
                all_variables = (
                    test_case["measured_variables"] + test_case["derived_variables"] + test_case["aggregated_variables"]
                )

                cli_args = [
                    "from-cross-product",
                    "--sites",
                    *test_case["sites"],
                    "--variables",
                    *all_variables,
                    "--periodicities",
                    *test_case["periodicities"],
                    "--network",
                    test_case["network"],
                    "--start-date",
                    test_case["start_date"],
                    "--end-date",
                    test_case["end_date"],
                ]

                with (
                    patch.object(EddyProRunner, "__init__", eddypro_mock_init),
                    patch.object(EddyProRunner, "run", eddypro_mock_run),
                ):
                    pipeline_main(cli_args)

            # get the outputs and save to disk
            all_keys = storage_client.list_keys(E2E_OUTPUT_BUCKET)
            for key in all_keys:
                expected_path = expected_output_dir / key
                result = pl.read_parquet(storage_client.get_bytes(E2E_OUTPUT_BUCKET, key))
                expected_path.parent.mkdir(parents=True, exist_ok=True)
                result.write_parquet(expected_path)


if __name__ == "__main__":
    main()
