"""
An orchestration class used to run for processing operations for corrections, quality control and infilling.
"""

import logging
from abc import ABC, abstractmethod

import polars as pl
import time_stream as ts

from dritimeseriesprocessor.models.domain_models.processing_config import (
    DataProcessingConfig,
    DataProcessingMethodConfig,
)
from dritimeseriesprocessor.models.domain_models.time_series_container import TimeSeriesContainer
from dritimeseriesprocessor.operations.flags.flag_methods import ensure_flag_column
from dritimeseriesprocessor.operations.flags.flag_names import core_flag_column_name
from dritimeseriesprocessor.utils.enums import ConfigurationType

logger = logging.getLogger(__name__)


class OperationPipeline(ABC):
    """A base class to define the workflow of operations such as corrections, QC, and infilling.

    Subclasses implement the operation specific components such as applying a method, computing flag masks,
    sorting configuration blocks, and constructing flag column names.
    """

    def __init__(self, operation_type: ConfigurationType, flag_systems: dict[str, dict[str, int]]):
        """Initialise the operation processor.

        Args:
            operation_type: Type of operation.
            flag_systems: Flag systems to register on the result before updating core flags.
        """
        self.operation_type = operation_type
        self.flag_systems = flag_systems

    @abstractmethod
    def apply(
        self, tf: ts.TimeFrame, config: DataProcessingMethodConfig, dataset_repository: dict[str, TimeSeriesContainer]
    ) -> ts.TimeFrame:
        """Apply a specific method to the time series data.

        Args:
            tf: Time series frame to process.
            config: Configuration that the method requires.
            dataset_repository: Repository for accessing additional datasets.

        Returns:
            Result of applying the method, format depends on implementation.
        """
        pass

    @abstractmethod
    def get_flag_column(self, column: str) -> str | None:
        """Determine the operation-specific flag column name for a given data column.

        This is the flag column the operation writes during processing (e.g. the QC flag column for
        quality control). Operations that do not produce their own flags (aggregation, derivation)
        return None.

        Args:
            column: Name of the data column.

        Returns:
            Name of the corresponding flag column, or None if this operation does not produce flags.
        """
        pass

    @abstractmethod
    def compute_flag_mask(self, tf: ts.TimeFrame, result: ts.TimeFrame, column_name: str) -> pl.Series | pl.Expr:
        """Compute a boolean mask indicating which values should be flagged.

        Args:
            tf: Original TimeFrame being processed.
            result: Result from applying a method to tf.
            column_name: Name of the column being processed.

        Returns:
            Boolean mask suitable as use in a Polars expression for flagging.
        """
        pass

    @abstractmethod
    def core_flag_updater(self, tf: ts.TimeFrame) -> ts.TimeFrame:
        """Update core flags after all methods are applied.

        Args:
            tf: TimeFrame with flags to update.

        Returns:
            Timeframe with updated core flags
        """
        pass

    def run(
        self,
        container: TimeSeriesContainer,
        dataset_repository: dict[str, TimeSeriesContainer],
        config: DataProcessingConfig,
    ) -> ts.TimeFrame:
        """Execute the full operation workflow on the time series container.

        Args:
            container: Time series container of metadata and data for the primary dataset to process.
            dataset_repository: Repository for accessing additional datasets.
            config: The data processing configuration to run.

        Returns:
            The updated TimeFrame after all operations and flag updates.
        """
        tf = container.data

        # Operations that process existing data write their flags onto it during ``apply`` (e.g. a correction writes
        # the corrections flag column), so make sure those flag columns exist first.
        # The incoming TimeFrame may be one generated by a previous step (e.g. an aggregation result), which only
        # carries the core flag system.
        # Generative operations (e.g. aggregation, derivation) start without data here and build a fresh TimeFrame
        # in apply, so there is nothing to set up yet.
        if tf is not None and container.has_flags():
            self._init_flag_columns(tf, container.flag_column_schemes)

        # Apply configs
        for cfg in config.method_configs:
            logger.info(f"Operation: {self.operation_type} | {cfg.method}")

            # Run the method. Generative operations (e.g. aggregation, derivation) accept tf=None and build a
            # fresh TimeFrame; every other operation receives the existing data set up above.
            tf = self.apply(tf=tf, config=cfg, dataset_repository=dataset_repository)  # type: ignore[arg-type]
            tf = self.apply_rounding(tf, cfg)

        # Every operation applies at least one method, so by this point tf is always a real TimeFrame.
        if tf is None:
            raise ValueError(f"Operation {self.operation_type} produced no data for: {container.ts_id}")

        if container.has_flags():
            # Generative operations (e.g. aggregation, derivation) built a new TimeFrame during ``apply`` with no
            # flagging, so set up its flag columns before updating core flags.
            # This is a "no-op" when this was already done before the loop.
            self._init_flag_columns(tf, container.flag_column_schemes)

            # Update core flags
            tf = self.core_flag_updater(tf)

        # Ensure time column name of tf is same as container's (not set for ObservationDatasets)
        if container.time_column_name is not None:
            tf = tf.rename_time_column(container.time_column_name)

        return tf

    def _init_flag_columns(self, tf: ts.TimeFrame, flag_column_schemes: dict[str, str]) -> None:
        """Create the flag columns this operation needs on the result TimeFrame.

        Every operation needs the core flag column. Operations that produce their own flags also need
        their operation-specific flag column (e.g. the QC flag column). Flag columns the dataset does
        not define, or that already exist, are skipped.

        Args:
            tf: The result TimeFrame to set up flag columns on.
            flag_column_schemes: Flag column names mapped to the flag system that they relate to.
        """
        for data_column in tf.data_columns:
            flag_columns = [core_flag_column_name(data_column)]

            operation_flag_column = self.get_flag_column(data_column)
            if operation_flag_column is not None:
                flag_columns.append(operation_flag_column)

            for flag_column in flag_columns:
                ensure_flag_column(tf, flag_column, self.flag_systems, flag_column_schemes)

    def _add_flag(self, tf: ts.TimeFrame, result: ts.TimeFrame, col_name: str, flag_name: str) -> None:
        """Apply a flag to the flag column

        Args:
            tf: TimeFrame containing original data.
            result: The result of the operation.
            col_name: Name of the parent column.
            flag_name: Type of flag to apply (must exist in the associated flag system).
        """
        flag_column = self.get_flag_column(col_name)
        if flag_column is None or flag_column not in tf.flag_columns:
            return

        mask = self.compute_flag_mask(tf, result, col_name)
        if mask is not None:
            result.add_flag(flag_column, flag_name, mask)

    @staticmethod
    def apply_rounding(tf: ts.TimeFrame, config: DataProcessingMethodConfig) -> ts.TimeFrame:
        """Apply any rounding to the resulting TimeFrame data (if required by metadata)

        Args:
            tf: TimeFrame containing data to round.
            config: Configuration options containing round parameter.

        Returns:
            TimeFrame with rounded data.
        """
        round_decimals: int | None = config.params.get("round")
        if round_decimals is None:
            return tf

        col_name = tf.metadata["column_name"]
        return tf.with_df(tf.df.with_columns(pl.col(col_name).round(round_decimals).alias(col_name)))
