name: CI/CD Pipeline

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Build venv
        run: |
          python -m venv .venv
          echo "VIRTUAL_ENV=./.venv" >> $GITHUB_ENV
          echo "PATH=./.venv/bin:$PATH" >> $GITHUB_ENV
      - name: Install Codebase
        run: |
          which python
          python -m pip install .
