name: Deploy the Docker Image to ECR

on:
  workflow_call:
    secrets:
      AWS_REGION:
        required: true
      AWS_ROLE_ARN:
        required: true
    
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp
